S5T7: Авторизация: регистрация и страница входа (уже с API, берите API из прошлого модуля).
SevillaTeam/crocodile pull request #10
Opened 2021-06-17 09:11 UTC by alex1056

**Формы можно посмотреть:** 

- /registration
- /authorization

2021-06-17 12:47 UTC, artbuzzon approved these changes

2021-06-19 15:42 UTC, bercly0b commented on .gitignore
> +package-lock.json
ой, давай не будем этот файл игнорить. его лучше в порядке держать, а то можно какой нибудь не очевидный баг с зависимостями словить, который потом очень сложно будет найти

2021-06-19 15:43 UTC, bercly0b commented on package.json
> +    "@types/validator": "^13.1.4",
это в `devDependencies` нужно перенести

2021-06-19 15:45 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const haveErrors = (errors: IErrors): boolean => {
эта функция не участвует в рендере. давай вынесем ее наружу компоненте. можно рядом с компонентом прям положить или можно файлик `utils` создать

2021-06-19 15:45 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const inputsHaveValues = (values: IValues) => {
тоже самое

2021-06-19 15:45 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const inputsHaveValues = (values: IValues) => {
https://github.com/SevillaTeam/crocodile/pull/10/files#r654810505

2021-06-19 15:46 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const validateForm = (errors: IErrors, values: IValues): boolean => {
https://github.com/SevillaTeam/crocodile/pull/10/files#r654810505

2021-06-19 15:46 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const validateForm = (errors: IErrors, values: IValues): boolean => {
валидатор можно вообще отдельно написать, он точно не только  в этом компоненте понадобится

2021-06-19 15:47 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const handleSubmit = (e: FormEvent<HTMLFormElement>): void => {
это нужно в обернуть в [useCallback](https://ru.reactjs.org/docs/hooks-reference.html#usecallback)

2021-06-19 15:47 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const onChange = ({ value, name }: IInputState): void => {
[useCallback](https://ru.reactjs.org/docs/hooks-reference.html#usecallback)

2021-06-19 15:47 UTC, bercly0b commented on src/components/LoginForm/login-form.tsx
> +  const validateField = (fieldName: string, value: string): boolean => {
тоже нужно в будущий валидатор вынести

2021-06-19 15:48 UTC, bercly0b commented on src/components/SignUpForm/index.ts
> +// export type { OwnSignUpFormProps } from './types';
лишнее?

2021-06-19 15:51 UTC, bercly0b commented on src/components/SignUpForm/signup-form.tsx
> +  const inputsHaveValues = (values: IValues) => {
если из `src/components/LoginForm/login-form.tsx` вынести логику валидации в отдельный модуль, то тут можно не копипастить, а просто заиспользовать этот модуль валидации

2021-06-19 15:51 UTC, bercly0b commented on src/components/router/router.tsx
> +      <Route path={['/']} exact component={Pages.Home} />
а почему массивом `path` передаем, а не просто строкой?

2021-06-19 15:54 UTC, bercly0b requested changes
пройдись по комментам пож. и еще нужно сделать ребейз по мастеру

2021-06-21 10:03 UTC, alex1056 commented on .gitignore
> +package-lock.json
Ок, понял что можно "концов" не найти ))

2021-06-21 10:03 UTC, alex1056 commented on package.json
> +    "@types/validator": "^13.1.4",
Ок

2021-06-21 10:04 UTC, alex1056 commented on src/components/LoginForm/login-form.tsx
> +  const haveErrors = (errors: IErrors): boolean => {
Ок, это относится к валидатору более, туда и вынес.

2021-06-21 10:04 UTC, alex1056 commented on src/components/LoginForm/login-form.tsx
> +  const inputsHaveValues = (values: IValues) => {
Сделал

2021-06-21 10:04 UTC, alex1056 commented on src/components/LoginForm/login-form.tsx
> +  const validateForm = (errors: IErrors, values: IValues): boolean => {
Написал валидатор отдельно

2021-06-21 10:04 UTC, alex1056 commented on src/components/LoginForm/login-form.tsx
> +  const handleSubmit = (e: FormEvent<HTMLFormElement>): void => {
сделано

2021-06-21 10:05 UTC, alex1056 commented on src/components/LoginForm/login-form.tsx
> +  const onChange = ({ value, name }: IInputState): void => {
сделано

2021-06-21 10:05 UTC, alex1056 commented on src/components/LoginForm/login-form.tsx
> +  const validateField = (fieldName: string, value: string): boolean => {
сделано

2021-06-21 10:06 UTC, alex1056 commented on src/components/SignUpForm/index.ts
> +// export type { OwnSignUpFormProps } from './types';
убрал

2021-06-21 10:06 UTC, alex1056 commented on src/components/SignUpForm/signup-form.tsx
> +  const inputsHaveValues = (values: IValues) => {
валидатор теперь отдельный

2021-06-21 10:07 UTC, alex1056 commented on src/components/router/router.tsx
> +      <Route path={['/']} exact component={Pages.Home} />
Изначально по нескольким path вызывался один компонент, сейчас это устранили, артефакты убрал.

2021-06-21 14:22 UTC, bercly0b approved these changes

2021-06-21 15:34 UTC, merged