S5T10: Обработка ошибок внутри «детей» React-компонентов.
SevillaTeam/crocodile pull request #5
Opened 2021-06-14 12:12 UTC by artbuzzon

2021-06-14 12:17 UTC, artbuzzon commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обработка ошибок внутри «детей» React-компонентов.](https://trello.com/c/nrXlX8fi/10-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA-%D0%B2%D0%BD%D1%83%D1%82%D1%80%D0%B8-%D0%B4%D0%B5%D1%82%D0%B5%D0%B9-react-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2)

2021-06-14 22:06 UTC, alex1056 commented
Все Ok

2021-06-14 22:09 UTC, alex1056 approved these changes

2021-06-15 09:19 UTC, bercly0b commented on src/app-components/ErrorBoundary/index.tsx
> +class ErrorBoundary extends Component<Props, State> {
а где используется этот компонент?

2021-06-15 09:19 UTC, bercly0b commented on src/app-components/ErrorBoundary/index.tsx
> +            return <h1>Sorry.. there was an error</h1>;
тут можно добавить ссылку на главную или куда нибудь. что бы можно было уйти с этой страницы

2021-06-15 09:20 UTC, bercly0b requested changes
надо заиспользовать этот компонет

2021-06-15 16:39 UTC, bercly0b approved these changes

2021-06-16 06:53 UTC, merged