S5T17: Базовый компонент input
SevillaTeam/crocodile pull request #8
Opened 2021-06-15 14:49 UTC by alex1056

2021-06-15 16:44 UTC, bercly0b commented on src/components/Input/input.module.scss
> +    // line-height: 16px;
если это лишнее, то давай удалим

2021-06-15 16:45 UTC, bercly0b commented on src/components/Input/input.tsx
> +export class Input extends PureComponent<Props> {
почему класс, а не функция?

2021-06-15 16:46 UTC, bercly0b commented on src/components/Input/input.tsx
> +            required
может `required` тоже снаружи передавать? и по дефолту `false` сделать наверное будет правильнее

2021-06-15 16:47 UTC, bercly0b commented on src/components/Input/input.tsx
> +          <span className={s.input__placeholder}>{placeholder}</span>
тут нужно сперва проверить что `placeholder` есть, потому что если его не передали то отрендерится пустой `span`

2021-06-15 16:47 UTC, bercly0b commented on src/components/Input/input.tsx
> +          {helpMessage}
тут тоже самое, нужно рендерить `span` только если есть `helpMessage`

2021-06-15 16:50 UTC, bercly0b commented on src/components/Input/types.ts
> +  onChange?: (e: FormEvent<HTMLInputElement>) => void;
`onChange` я бы сделал обязательным аргументом. потому что без него инпут не имеет смысла. и лучше бы сделать так, что бы в него передавался не весь ивент, а только строка-значение инпута.

ну то есть я предлагаю работу с ивентом инкапсулировать внутри инпута. что бы в многочисленных местах использования инпута не заниматься этим

2021-06-15 16:54 UTC, bercly0b commented on src/components/Input/input.tsx
> +      onChange,
смотри, в текущей реализации компонент не запоминает свое состояни (введенный текст) и придется работать с dom ивентом. это называется не контролируемый компонент.  

а нам нужно сделать его контролируемым, то есть абстрагироваться от работы с дом, что бы все данные были в реакте. 

для этого нужно при вводе текста в инпут запомнимать значение в стейте компонента. и рендерить это значение в `value` у `input`. таким образом получится что мы будем в любой момент времени знать что введено в инпут, сможет это значение передавать наружу (в коллбек `onChange`) и снаружи ни как не будем взаимодействовать с dom событием

2021-06-15 16:55 UTC, bercly0b requested changes
есть вопросики. пройдись пож по коментам

2021-06-15 18:12 UTC, alex1056 commented on src/components/Input/input.tsx
> +export class Input extends PureComponent<Props> {
Полагаю, нет принципиальной разницы. Поэтому решил сделать класс. Если для чего-то нужен FC - готов переделать.

2021-06-16 10:33 UTC, alex1056 commented on src/components/Input/input.module.scss
> +    // line-height: 16px;
сделал

2021-06-16 10:34 UTC, alex1056 commented on src/components/Input/input.tsx
> +            required
Сделано

2021-06-16 10:34 UTC, alex1056 commented on src/components/Input/input.tsx
> +          <span className={s.input__placeholder}>{placeholder}</span>
сделано

2021-06-16 10:34 UTC, alex1056 commented on src/components/Input/input.tsx
> +          {helpMessage}
сделано

2021-06-16 10:34 UTC, alex1056 commented on src/components/Input/types.ts
> +  onChange?: (e: FormEvent<HTMLInputElement>) => void;
сделано

2021-06-16 10:35 UTC, alex1056 commented on src/components/Input/input.tsx
> +      onChange,
input сделал контролируемым

2021-06-16 10:40 UTC, artbuzzon commented on src/components/Input/input.tsx
> +export class Input extends PureComponent<Props> {
Договорились функциональные делать. Посмотри, плиз, в слаке - я спрашивал у Влада.
Можно сделать и так и так, но сейчас все идет к функциональным компонентам и не только в реакте

2021-06-17 12:51 UTC, artbuzzon approved these changes

2021-06-19 15:41 UTC, bercly0b approved these changes

2021-06-19 15:41 UTC, merged